name: build

permissions:
    contents: read
    packages: write

on: [workflow_dispatch, push]

env:
    CMAKE_PARAMS: -DSDL_AUDIO:BOOL="0" -DSDL_HIDAPI_JOYSTICK:BOOL="1" -DSDL_MISC:BOOL="0" -DSDL_DUMMYAUDIO:BOOL="0" -DSDL_RENDER:BOOL="0" -DSDL_ALTIVEC:BOOL="0" -DSDL_CPUINFO:BOOL="0" -DSDL_SHARED:BOOL="1" -DSDL_OPENGL:BOOL="0" -DSDL_VULKAN:BOOL="0" -DSDL_DIRECTX:BOOL="0" -DSDL_RENDER_D3D:BOOL="0" -DSDL_FILE:BOOL="0" -DSDL_DUMMYVIDEO:BOOL="0" -DSDL_LOADSO:BOOL="0" -DSDL_OPENGLES:BOOL="0" -DSDL_TEST:BOOL="0" -DSDL_FILESYSTEM:BOOL="0" -DSDL_OFFSCREEN:BOOL="0" -DSDL_VIDEO:BOOL="0" -DSDL_DISKAUDIO:BOOL="0" -DSDL_POWER:BOOL="0" -DSDL_WASAPI:BOOL="0" -DSDL_ATOMIC:BOOL="0" 

jobs:
    build_native_linux:
        runs-on: ubuntu-22.04
        steps: 
            - uses: actions/checkout@v4
            - name: Clone Submodules
              run: git submodule update --init --recursive --remote
            - name: Install Build Tools
              run: sudo apt-get install -y cmake
            - name: CMake Configure
              run:  cmake -B build ${{CMAKE_PARAMS}}
              working-directory: SDL2_Native
            - name: CMake Build
              run: cmake --build . --config Release
              working-directory: SDL2_Native/build
            - name: Make Output Folder
              shell: bash
              run: |
                mkdir -p build_native/linux-x64
                cp SDL2_Native/build/*.a build_native/linux-x64
                cp SDL2_Native/build/libSDL2-2.0.so build_native/linux-x64
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: native-linux-x64
                path: build_native