name: build

permissions:
  contents: read
  packages: write

on: workflow_dispatch

jobs:
  build_native:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            rid: linux-x64
            additionalconfig: sudo apt-get install -y cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libfribidi-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev libthai-dev libusb-1.0-0-dev
            cmakeargs: -B build -DSDL_X11_XINPUT:BOOL="0" -DSDL_X11_SHARED:BOOL="0" -DSDL_VIDEO:BOOL="0" -DSDL_X11_XCURSOR:BOOL="0" -DSDL_WAYLAND:BOOL="0" -DSDL_X11:BOOL="0" -DSDL_X11_XFIXES:BOOL="0" -DSDL_WAYLAND_SHARED:BOOL="0" -DSDL_X11_XDBE:BOOL="0" -DSDL_RENDER:BOOL="0" -DSDL_X11_XSCRNSAVER:BOOL="0" -DSDL_WAYLAND_LIBDECOR:BOOL="0" -DSDL_WAYLAND_LIBDECOR_SHARED:BOOL="0" -DSDL_X11_XRANDR:BOOL="0" -DSDL_X11_XSHAPE:BOOL="0" -DSDL_WAYLAND_QT_TOUCH:BOOL="0" 
            linkerfiles: SDL2_Native/build/*.a
            libfiles: SDL2_Native/build/libSDL2-2.0.so
          - os: windows-2022
            rid: win-x64
            additionalconfig: echo "Hi there."
            cmakeargs: -B build -A x64 DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
            linkerfiles: SDL2_Native/build/Release/SDL2-static.lib
            libfiles: SDL2_Native/build/Release/SDL2.dll
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Clone Submodules
        run: git submodule update --init
      - name: Install Tools
        run: ${{ matrix.additionalconfig }}
      - name: CMake Configure
        run: cmake ${{ matrix.cmakeargs }}
        working-directory: SDL2_Native
      - name: CMake Build
        run: cmake --build . --config Release -j
        working-directory: SDL2_Native/build
      - name: Make Output Folder
        run: |
         mkdir -p build_native/${{ matrix.rid }}
         cp ${{ matrix.linkerfiles }} build_native/${{ matrix.rid }}
         cp ${{ matrix.libfiles }} build_native/${{ matrix.rid }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: native-${{ matrix.rid }}
          path: build_native
  pack:
    runs-on: ubuntu-22.04
    needs: build_native
    steps:
      - uses: actions/checkout@v6
      - name: Get Native Artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: native-*
          path: build-native
          merge-multiple: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: pack
        run: dotnet pack -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
        working-directory: SDLControllerWrapper
      - name: Make Output Folder
        run: |
          mkdir -p build_managed
          cp SDLControllerWrapper/bin/Release/*.nupkg build_managed
          cp SDLControllerWrapper/bin/Release/*.snupkg build_managed
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: SDLControllerWrapper
          path: build_managed
