name: build

permissions:
  contents: read
  packages: write

on: workflow_dispatch

jobs:
  build_native:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            rid: linux-x64
            additionalconfig: sudo apt-get install -y cmake
            cmakeargs: -B build -DSDL_UNIX_CONSOLE_BUILD=ON
            linkerfiles: SDL2_Native/build/*.a
            libfiles: SDL2_Native/build/libSDL2-2.0.so
          - os: windows-2022
            rid: win-x64
            additionalconfig: echo "Hi there."
            cmakeargs: -B build -A x64
            linkerfiles: SDL2_Native/build/Release/SDL2-static.lib
            libfiles: SDL2_Native/build/Release/SDL2.dll
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Clone Submodules
        run: git submodule update --init
      - name: Install Tools
        run: ${{ matrix.additionalconfig }}
      - name: CMake Configure
        run: cmake ${{ matrix.cmakeargs }}
        working-directory: SDL2_Native
      - name: CMake Build
        run: cmake --build . --config Release -j
        working-directory: SDL2_Native/build
      - name: Make Output Folder
        run: |
         mkdir -p build_native/${{ matrix.rid }}
         cp ${{ matrix.linkerfiles }} build_native/${{ matrix.rid }}
         cp ${{ matrix.libfiles }} build_native/${{ matrix.rid }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: native-${{ matrix.rid }}
          path: build_native
  pack:
    runs-on: ubuntu-22.04
    needs: build_native
    steps:
      - uses: actions/checkout@v6
      - name: Get Native Artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: native-*
          path: build-native
          merge-multiple: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
      - name: pack
        run: dotnet pack -c Release -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
        working-directory: SDLControllerWrapper
      - name: Make Output Folder
        run: |
          mkdir -p build_managed
          cp SDLControllerWrapper/bin/Release/*.nupkg build_managed
          cp SDLControllerWrapper/bin/Release/*.snupkg build_managed
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: SDLControllerWrapper
          path: build_managed
